# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cars_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1285, 845)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #2b0f0f; /* mørk rødbrun, som marsjord */\n"
"    color: #ffcc99; /* sandfarget tekst */\n"
"    font-family: \'Orbitron\', \'Share Tech Mono\', sans-serif;\n"
"    font-size: 14pt;\n"
"}\n"
"\n"
"/* Mars-knapper */\n"
"QPushButton {\n"
"    background-color: #5c1e1e;\n"
"    color: #ff6f3c;\n"
"    border: 2px solid #ff6f3c;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    text-transform: uppercase;\n"
"    text-shadow: 0 0 6px #ff6f3c;\n"
"    box-shadow: 0 0 12px #ff6f3c;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff6f3c;\n"
"    color: #2b0f0f;\n"
"    box-shadow: 0 0 20px #ff6f3c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff3c1f;\n"
"    box-shadow: inset 0 0 10px #ff6f3c;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #ffcc99;\n"
"    font-size: 16pt;\n"
"    text-shadow: 0 0 8px #ffcc99;\n"
"}\n"
"\n"
"/* GroupBox styling */\n"
"QGroupBox {\n"
"    border: 2px solid #ff6f3c;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"    color: #ff6f3c;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px;\n"
"}\n"
"\n"
"/* Logg-terminal */\n"
"QTextEdit {\n"
"    background-color: #1a0a0a;\n"
"    color: #ffcc99;\n"
"    font-family: \'Share Tech Mono\';\n"
"    font-size: 12pt;\n"
"    border: 1px solid #ff6f3c;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 2721, 861))
        self.tabWidget.setObjectName("tabWidget")
        self.GUI = QtWidgets.QWidget()
        self.GUI.setObjectName("GUI")
        self.groupBox_2 = QtWidgets.QGroupBox(self.GUI)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 420, 341, 111))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.btnOpenLog = QtWidgets.QPushButton(self.groupBox_2)
        self.btnOpenLog.setObjectName("btnOpenLog")
        self.gridLayout.addWidget(self.btnOpenLog, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.GUI)
        self.groupBox.setGeometry(QtCore.QRect(360, 540, 451, 151))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnOn = QtWidgets.QPushButton(self.groupBox)
        self.btnOn.setObjectName("btnOn")
        self.gridLayout_2.addWidget(self.btnOn, 1, 1, 1, 1)
        self.btnOff = QtWidgets.QPushButton(self.groupBox)
        self.btnOff.setObjectName("btnOff")
        self.gridLayout_2.addWidget(self.btnOff, 1, 2, 1, 1)
        self.btnAuto = QtWidgets.QPushButton(self.groupBox)
        self.btnAuto.setObjectName("btnAuto")
        self.gridLayout_2.addWidget(self.btnAuto, 0, 1, 1, 1)
        self.btnGuard = QtWidgets.QPushButton(self.groupBox)
        self.btnGuard.setObjectName("btnGuard")
        self.gridLayout_2.addWidget(self.btnGuard, 0, 2, 1, 1)
        self.lblVideoStream = QtWidgets.QLabel(self.GUI)
        self.lblVideoStream.setGeometry(QtCore.QRect(360, 0, 911, 541))
        self.lblVideoStream.setStyleSheet("background-color: black;")
        self.lblVideoStream.setText("")
        self.lblVideoStream.setObjectName("lblVideoStream")
        self.groupBox_3 = QtWidgets.QGroupBox(self.GUI)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 341, 411))
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTemperature = QtWidgets.QLabel(self.groupBox_3)
        self.lblTemperature.setObjectName("lblTemperature")
        self.verticalLayout.addWidget(self.lblTemperature)
        self.lblHum = QtWidgets.QLabel(self.groupBox_3)
        self.lblHum.setObjectName("lblHum")
        self.verticalLayout.addWidget(self.lblHum)
        self.lblLedStatus = QtWidgets.QLabel(self.groupBox_3)
        self.lblLedStatus.setObjectName("lblLedStatus")
        self.verticalLayout.addWidget(self.lblLedStatus)
        self.lblArduinoMode = QtWidgets.QLabel(self.groupBox_3)
        self.lblArduinoMode.setObjectName("lblArduinoMode")
        self.verticalLayout.addWidget(self.lblArduinoMode)
        self.lblDrivingMode = QtWidgets.QLabel(self.groupBox_3)
        self.lblDrivingMode.setObjectName("lblDrivingMode")
        self.verticalLayout.addWidget(self.lblDrivingMode)
        self.groupBox_4 = QtWidgets.QGroupBox(self.GUI)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 540, 341, 151))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnTakePhoto = QtWidgets.QPushButton(self.groupBox_4)
        self.btnTakePhoto.setMinimumSize(QtCore.QSize(0, 110))
        self.btnTakePhoto.setObjectName("btnTakePhoto")
        self.gridLayout_3.addWidget(self.btnTakePhoto, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.GUI)
        self.groupBox_5.setGeometry(QtCore.QRect(820, 540, 451, 151))
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnControlDrivingMode = QtWidgets.QPushButton(self.groupBox_5)
        self.btnControlDrivingMode.setObjectName("btnControlDrivingMode")
        self.gridLayout_4.addWidget(self.btnControlDrivingMode, 0, 1, 1, 2)
        self.btnAutonomousDrivingMode = QtWidgets.QPushButton(self.groupBox_5)
        self.btnAutonomousDrivingMode.setObjectName("btnAutonomousDrivingMode")
        self.gridLayout_4.addWidget(self.btnAutonomousDrivingMode, 1, 1, 1, 2)
        self.txtLog = QtWidgets.QTextEdit(self.GUI)
        self.txtLog.setGeometry(QtCore.QRect(10, 700, 1261, 101))
        self.txtLog.setStyleSheet("")
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName("txtLog")
        self.tabWidget.addTab(self.GUI, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.sense_hat_group_box = QtWidgets.QGroupBox(self.tab)
        self.sense_hat_group_box.setGeometry(QtCore.QRect(380, 10, 481, 161))
        self.sense_hat_group_box.setObjectName("sense_hat_group_box")
        self.lblTemperature_Sense_HAT = QtWidgets.QLabel(self.sense_hat_group_box)
        self.lblTemperature_Sense_HAT.setGeometry(QtCore.QRect(10, 20, 461, 41))
        self.lblTemperature_Sense_HAT.setObjectName("lblTemperature_Sense_HAT")
        self.lblHumidity_Sense_HAT = QtWidgets.QLabel(self.sense_hat_group_box)
        self.lblHumidity_Sense_HAT.setGeometry(QtCore.QRect(10, 60, 461, 51))
        self.lblHumidity_Sense_HAT.setMinimumSize(QtCore.QSize(319, 0))
        self.lblHumidity_Sense_HAT.setObjectName("lblHumidity_Sense_HAT")
        self.lblPressuseSenseHAT = QtWidgets.QLabel(self.sense_hat_group_box)
        self.lblPressuseSenseHAT.setGeometry(QtCore.QRect(10, 100, 461, 51))
        self.lblPressuseSenseHAT.setMinimumSize(QtCore.QSize(319, 0))
        self.lblPressuseSenseHAT.setObjectName("lblPressuseSenseHAT")
        self.sense_hat_group_box_2 = QtWidgets.QGroupBox(self.tab)
        self.sense_hat_group_box_2.setGeometry(QtCore.QRect(440, 330, 361, 91))
        self.sense_hat_group_box_2.setObjectName("sense_hat_group_box_2")
        self.lblTemperatureRPi4Processor = QtWidgets.QLabel(self.sense_hat_group_box_2)
        self.lblTemperatureRPi4Processor.setGeometry(QtCore.QRect(10, 30, 341, 51))
        self.lblTemperatureRPi4Processor.setObjectName("lblTemperatureRPi4Processor")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(860, 310, 401, 141))
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblTemperature_2 = QtWidgets.QLabel(self.groupBox_6)
        self.lblTemperature_2.setObjectName("lblTemperature_2")
        self.verticalLayout_2.addWidget(self.lblTemperature_2)
        self.lblHum_2 = QtWidgets.QLabel(self.groupBox_6)
        self.lblHum_2.setObjectName("lblHum_2")
        self.verticalLayout_2.addWidget(self.lblHum_2)
        self.lblLedStatus_2 = QtWidgets.QLabel(self.groupBox_6)
        self.lblLedStatus_2.setObjectName("lblLedStatus_2")
        self.verticalLayout_2.addWidget(self.lblLedStatus_2)
        self.sense_hat_group_box_3 = QtWidgets.QGroupBox(self.tab)
        self.sense_hat_group_box_3.setGeometry(QtCore.QRect(480, 700, 271, 91))
        self.sense_hat_group_box_3.setObjectName("sense_hat_group_box_3")
        self.lblCamStatus = QtWidgets.QLabel(self.sense_hat_group_box_3)
        self.lblCamStatus.setGeometry(QtCore.QRect(10, 20, 251, 61))
        self.lblCamStatus.setObjectName("lblCamStatus")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 340, 341, 81))
        self.groupBox_7.setStyleSheet("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lblDrivingMode_2 = QtWidgets.QLabel(self.groupBox_7)
        self.lblDrivingMode_2.setObjectName("lblDrivingMode_2")
        self.gridLayout_5.addWidget(self.lblDrivingMode_2, 0, 0, 1, 1)
        self.graphicsBackground = QtWidgets.QGraphicsView(self.tab)
        self.graphicsBackground.setGeometry(QtCore.QRect(5, 1, 1271, 801))
        self.graphicsBackground.setObjectName("graphicsBackground")
        self.sense_hat_group_box_4 = QtWidgets.QGroupBox(self.tab)
        self.sense_hat_group_box_4.setGeometry(QtCore.QRect(980, 700, 281, 91))
        self.sense_hat_group_box_4.setObjectName("sense_hat_group_box_4")
        self.lblLidarStatus_3 = QtWidgets.QLabel(self.sense_hat_group_box_4)
        self.lblLidarStatus_3.setGeometry(QtCore.QRect(30, 20, 241, 67))
        self.lblLidarStatus_3.setObjectName("lblLidarStatus_3")
        self.graphicsBackground.raise_()
        self.sense_hat_group_box.raise_()
        self.sense_hat_group_box_2.raise_()
        self.groupBox_6.raise_()
        self.sense_hat_group_box_3.raise_()
        self.groupBox_7.raise_()
        self.sense_hat_group_box_4.raise_()
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "LOG"))
        self.btnOpenLog.setText(_translate("MainWindow", "OPEN LOG"))
        self.groupBox.setTitle(_translate("MainWindow", "ARDUINO SENSOR MODE"))
        self.btnOn.setText(_translate("MainWindow", "ON"))
        self.btnOff.setText(_translate("MainWindow", "OFF"))
        self.btnAuto.setText(_translate("MainWindow", "AUTO"))
        self.btnGuard.setText(_translate("MainWindow", "GUARD"))
        self.groupBox_3.setTitle(_translate("MainWindow", "STATUS"))
        self.lblTemperature.setText(_translate("MainWindow", "Temperatur: lblTemp"))
        self.lblHum.setText(_translate("MainWindow", "Luftfuktighet: lblHum"))
        self.lblLedStatus.setText(_translate("MainWindow", "LED: lblLedStatus"))
        self.lblArduinoMode.setText(_translate("MainWindow", "Arduino Mode: lblArduinoMode"))
        self.lblDrivingMode.setText(_translate("MainWindow", "Driving Mode: lblDrivingMode"))
        self.groupBox_4.setTitle(_translate("MainWindow", "CAMERA CONTROLLER"))
        self.btnTakePhoto.setText(_translate("MainWindow", "TAKE PHOTO"))
        self.groupBox_5.setTitle(_translate("MainWindow", "DRIVING MODE"))
        self.btnControlDrivingMode.setText(_translate("MainWindow", "JOYSTICK"))
        self.btnAutonomousDrivingMode.setText(_translate("MainWindow", "AUTONOMOUS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GUI), _translate("MainWindow", "GUI"))
        self.sense_hat_group_box.setTitle(_translate("MainWindow", "NODE SENSE HAT w/ IMU"))
        self.lblTemperature_Sense_HAT.setText(_translate("MainWindow", "Engine temperature: lblTemperature_Sense_HAT"))
        self.lblHumidity_Sense_HAT.setText(_translate("MainWindow", "Engine humidity: lblHumidity_Sense_HAT"))
        self.lblPressuseSenseHAT.setText(_translate("MainWindow", "Pressure: lblPresure"))
        self.sense_hat_group_box_2.setTitle(_translate("MainWindow", "RASPBERRY PI4"))
        self.lblTemperatureRPi4Processor.setText(_translate("MainWindow", "RPi4 processor temperature: lblTemperature_Sense_HAT"))
        self.groupBox_6.setTitle(_translate("MainWindow", "UART ARDUINO W/ SENSOR STATUS"))
        self.lblTemperature_2.setText(_translate("MainWindow", "Teemperatur: lblTemp"))
        self.lblHum_2.setText(_translate("MainWindow", "Luftfuktighet: lblHum"))
        self.lblLedStatus_2.setText(_translate("MainWindow", "LED: lblLedStatus"))
        self.sense_hat_group_box_3.setTitle(_translate("MainWindow", "IR CAMERA"))
        self.lblCamStatus.setText(_translate("MainWindow", "CAM: lblCamStatus"))
        self.groupBox_7.setTitle(_translate("MainWindow", "TOPIC /DRIVING_MODE"))
        self.lblDrivingMode_2.setText(_translate("MainWindow", "Driving Mode: lblDrivingMode"))
        self.sense_hat_group_box_4.setTitle(_translate("MainWindow", "LiDAR Node"))
        self.lblLidarStatus_3.setText(_translate("MainWindow", "LiDAR: lblLidarStatus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "SYSTEM STATUS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
